---
# tasks file for apache
- name: install apache
  yum: name=httpd state=present

- name: create sites directories
  file: path={{item}} state=directory
  with_items: "{{apache_dirs}}"

- name: copy index.html
  template: src=index.html.j2 dest={{apache_docroot}}/index.html

- name: copy httpd conf
  template: src=httpd.conf-{{ansible_os_family}}.j2 dest={{apache_config}}
  notify: restart apache

- name: start apache
  service: name=httpd state=started enabled=yes
